## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf

def configure(conf):
    ns3waf.check_modules(conf, ['core',  'internet', 'point-to-point', 'fd-net-device', 'lte', 'wifi'], mandatory = True)
#, 'dce-quagga'
#
def build(bld):
    bld.build_a_script('dce', needed = ['core',  'internet', 'point-to-point', 'fd-net-device', 'dce', 'flow-monitor', 'lte', 'wifi'],
				  target='bin/oneNewLTE',
				  source=['oneNewLTE.cc']
				  )

